name: CD devops 2026

on:
  workflow_run:
    workflows: ["CI devops 2026"]
    types:
      - completed
    branches:
      - main  
  
jobs:
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database
          tags: |
            # Tag latest
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # Tag short SHA
            type=sha,format=short

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./tp1-fullstack-app/database
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.ref == 'refs/heads/main' }}


  build-and-push-docker-image-backend:
    needs: sonar-analysis
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api
          tags: |
            # Tag latest
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # Tag short SHA
            type=sha,format=short
            
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./tp1-fullstack-app/backend/simpleapi
          # Note: tags has to be all lower-case
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.ref == 'refs/heads/main' }}


  build-and-push-docker-image-httpd:
    needs: sonar-analysis
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-24.04
    
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd
          tags: |
            # Tag latest
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # Tag short SHA
            type=sha,format=short

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./tp1-fullstack-app/httpd
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.ref == 'refs/heads/main' }}



